apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "in-cluster"
  template:
    metadata:
      name: prometheus
    spec:
      project: default
      source:
        repoURL: 'https://github.com/prometheus-community/helm-charts.git'
        chart: prometheus-community/prometheus
        targetRevision: 25.29.0
        helm:
          releaseName: prometheus
          values: |                                  # Optional custom values.yaml content
            persistence:
              enabled: true
              size: 8Gi
            resources:
              requests:
                memory: "512Mi"
                cpu: "700m"
              limits:
                memory: "1Gi"
                cpu: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: default                           # Target namespace
      syncPolicy:
        automated:
          prune: true                                # Remove obsolete resources
          selfHeal: true                             # Automatically fix drift

