name: Install Prometheus Operator using Terraform and Helm in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-prometheus-operator:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

      - name: Terraform Init
        run: terraform init -chdir=monitoring

      - name: Terraform Plan
        run: terraform plan -chdir=monitoring

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -chdir=monitoring
