name: Install Prometheus Operator using Terraform and Helm in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-prometheus-operator:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Run Helm in Docker
        run: |
            docker run --rm \
            --user $(id -u):$(id -g) \
            --network host \
            -v ${{ github.workspace }}/monitoring:/workspace \
            -v $HOME/.kube:/root/.kube \
            -v $HOME/.terraform.d:/root/.terraform.d \
            -w /workspace \
            alpine:3.20 \
            sh -c "
              apk add --no-cache curl bash tar gzip;
              curl https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz | tar zxvf -;
              mv linux-amd64/helm /usr/local/bin/helm;
              curl -sO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip;
              unzip terraform_1.0.0_linux_amd64.zip;
              chmod +x terraform;
              cd /workspace;
              ./terraform init;
              ./terraform apply -auto-approve;
            "
