name: Install Prometheus Operator using Terraform and Helm in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-prometheus-operator:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Run Helm in Docker
        run: |
            docker run --rm \
            --network host \
            -v ${{ github.workspace }}/monitoring:/workspace \
            -v $HOME/.kube:/root/.kube \
            alpine:3.20 \
            sh -c "
              apk add --no-cache curl bash tar gzip;
            "
